resources:
  - name: r_github 
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/newTest
pipelines:
  - name: pipeline_test
    steps:
      - name: cpp
        type: Bash
        configuration:
          inputResources:
            - name: r_github
          runtime:
            type: image
            image:
              auto:
                language: go
                versions: 
                  - 1.11.1
        execution:
          onExecute:
            - printenv
