resources:
  - name: Image_test
    type: Image
    configuration:
       registry: docker_chaitanya
       imageName: imageRepo/imageName
       imageTag: initial
  - name: gitResource_test
    type: GitRepo
    configuration:
      gitProvider: git_chaitanya
      path: ChaitanyaVootla/ymlTest
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: myBuild
      buildNumber: 123
  - name: webhookIntegrationResource
    type: Webhook
    configuration:
      webhookName: myInternal
      payload: "webhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegrationwebhookIntegration"
  - name: RemoteFile
    type: RemoteFile
    configuration:      
      source: dummyFileServer
      fileLocation: 'fileLocation_test'
      fileName: 'fileName_test'
      fileDateTime: 'fileDateTime_test'
pipelines:
  - name: res_test
    steps:
      - name: job
        type: Bash
        configuration:
          affinityGroup: bldGroupTest
          priority: 0
          inputResources:
            - name: Image_test
            - name: gitResource_test
            - name: myBuildInfo
            - name: webhookIntegrationResource
            - name: RemoteFile
        execution:
          onExecute:
            - echo "asd"
