resources:
  - name: Image_test
    type: Image
    configuration:
       registry: docker_chaitanya
       imageName: imageRepo/imageName
       imageTag: initial
  - name: gitResource_test
    type: GitRepo
    configuration:
      gitProvider: git_chaitanya
      path: ChaitanyaVootla/ymlTest
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: myBuild
      buildNumber: 123
pipelines:
  - name: res_test
    steps:
      - name: job
        type: Bash
        configuration:
          affinityGroup: bldGroupTest
          priority: 0
          inputResources:
            - name: Image_test
            - name: gitResource_test
        execution:
          onExecute:
            - echo "asd"
