resources:
  - name: gitrepo_res
    type: gitRepo
    repoPath: ChaitanyaVootla/newTest
    configuration:
      integrationName: git
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res
    type: file
    fileUrl: https://github.com/ankul-shippable/sample_java/blob/master/shippable.yml
    configuration:
      integrationName: git
    initialVersion:
      fileName: shippable.yml
      fileDtTm: random_value
 
  - name: image_res
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker
    initialVersion:
      imageTag: latest

   - name: sample_java_webhook_test
     type: webhook
     configuration:
       integrationName: git
     initialVersion:
       payload: test_payload
   - name: sample_java_kube_test
     type: cluster
     configuration:
       integrationName: docker
       bastionHostIP: 1.2.3.4
       bastionUser: sshUser
       bastionIntegrationName: sshKey-int
pipelines:
  - name: pipe_1
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - gitrepo_res 
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res

      - name: step1_B
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          resources:
            - file_res 
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_C
        type: bash
        configuration:
          affinityGroup: test_group      
        setup:
          runtime: onHost
        triggeredBy:
          steps:
            - step1_A 
        requires:
          integrations:
            - docker
          resources:
            - image_res
            - sample_java_webhook_test
            - sample_java_kube_test
        execution:
          onExecute:
            - echo "executing..."
