resources:
  - name: gitrepo_res_chaitanya
    type: gitRepo
    repoPath: ChaitanyaVootla/newTest
    configuration:
      integrationName: git_chaitanya
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res_chaitanya
    type: file
    fileLocation: https://github.com/ankul-shippable/sample_java/blob/master/shippable.yml
    configuration:
      integrationName: git_chaitanya
    initialVersion:
      fileName: shippable.yml
      fileDtTm: random_value

  - name: image_res_chaitanya
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker_chaitanya
    initialVersion:
      imageTag: latest

  - name: stateResource
    type: state

  - name: webhookRes
    type: webhook
    configuration:
      integrationName: docker_chaitanya
    initialVersion:
      payload: "asd"

  - name: clusterRes
    type: cluster
    configuration:
      integrationName: docker_chaitanya
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration

pipelines:
  - name: chaitanya_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step1_A
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_chaitanya
          resources:
            - image_res_chaitanya
        triggeredBy:
          resources:
            - gitrepo_res_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res_chaitanya

      - name: step1_B2
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        triggeredBy:
          resources:
            - file_res_chaitanya
            - webhookRes
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_C
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        triggeredBy:
          steps:
            - step1_A
        execution:
          onExecute:
            - echo "executing..."

      - name: step1_D
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        triggeredBy:
          resources:
            - clusterRes
          steps:
            - step1_B2
        execution:
          onExecute:
            - echo "executing..."

  - name: state_pipeline
    setup:
      runtime: onHost
    steps:
      - name: stateTest
        type: bash
        configuration:
          affinityGroup: state_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        triggeredBy:
          resources:
            - stateResource
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          # - file_res_chaitanya
          - stateResource
      - name: stateTest2
        type: bash
        configuration:
          affinityGroup: state_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        triggeredBy:
          steps:
            - stateTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          # - file_res_chaitanya
          - stateResource